# Generated by Django 5.1.1 on 2024-09-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_client_email_client_alter_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, help_text='введите имя получателя рассылки <br> ytkjl', max_length=100, null=True, verbose_name='Имя'),
        ),
    ]
