# Generated by Django 5.1.1 on 2024-09-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_alter_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email_client',
            field=models.EmailField(help_text='(обязятельно)', max_length=254, unique=True, verbose_name='электронная почта'),
        ),
    ]
