# Generated by Django 5.1.1 on 2024-09-25 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_mail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mail',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.RemoveField(
            model_name='mail',
            name='body',
        ),
        migrations.AddField(
            model_name='mail',
            name='client',
            field=models.ManyToManyField(to='mailing.client', verbose_name='Клиенты'),
        ),
        migrations.AddField(
            model_name='mail',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.letter', verbose_name='Cообщение'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='title',
            field=models.CharField(max_length=100, verbose_name='название рассылки'),
        ),
    ]
