# Generated by Django 5.1.1 on 2024-09-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0009_alter_mail_options_remove_mail_body_mail_client_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mail',
            options={'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.RemoveField(
            model_name='mail',
            name='client',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='message',
        ),
        migrations.AddField(
            model_name='mail',
            name='massage',
            field=models.TextField(blank=True, null=True, verbose_name='содержимое'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Тема письма'),
        ),
    ]
