# Generated by Django 5.1.1 on 2024-09-25 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0011_remove_mail_massage_mail_client_mail_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='client',
            new_name='clienty',
        ),
    ]
